## Numpy is python library for efficient numerical data manipulation.

In [2]:
# one-dimensional array
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
arr1 = np.arange(10, 21, 2) # using arrange to create a np arr you can do also np.array([i for i in range(10, 21, 2)])using list comprehension to create a np arr
print(arr1)

[1 2 3 4 5]
[10 12 14 16 18 20]


In [3]:
# two-dimensional array
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [7]:
# three-dimensional array
arr3 = np.array([
    [[1,2,3,4,5],[1,2,3,4,5]],
    [[1,2,3,4,5],[1,2,3,4,5]]
])
print(arr3)

[[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]]


In [15]:
# operations
a = np.array([1,2,3])
b = np.array([1,4,5])
 # addition
print("addition: " + str(a + b))
# subtraction
print("subtraction: " + str(a - b))
# multiplication
print("multiplication: " + str(a * b))
# division
print("division: " + str(a / b))
# scalar multiplication
print("scalar multiplication: " + str(np.dot(a, b)))

addition: [2 6 8]
subtraction: [ 0 -2 -2]
multiplication: [ 1  8 15]
division: [1.  0.5 0.6]
scalar multiplication: 24


In [23]:
# matrix multiplication
a = np.array([[1,2],[4, 5]])
b = np.array([[7, 8], [10,11]])
print("matrix multiplication: " + str(np.dot(a, b)))
print("matrix addition: " + str(a + b))

# hadamard product
print("hadamard product: " + str(a * b))

matrix multiplication: [[27 30]
 [78 87]]
matrix addition: [[ 8 10]
 [14 16]]
hadamard product: [[ 7 16]
 [40 55]]


In [26]:
# indexing
arr1 = np.arange(10)
arr2 = np.array([[3,4,5],[1,2,5]])
arr3 = np.array([
    [[1,2,3,4,5],[1,2,3,4,5]],
    [[1,2,3,4,5],[1,2,3,4,5]]
])
print(arr1[0])
print(arr2[0,0])
print(arr3[0,0,0])

[1 2]
1
5


In [29]:
# slicing

print(arr1[0:3])
print(arr2[0,2])
print(arr3[0,0,0:3])

[0 1 2]
5
[1 2 3]


In [32]:
# reshape
print("reshape arr1", arr1.reshape(2,5))
print("reshape arr2", arr2.reshape(3,2))
print("reshape arr3", arr3.reshape(2,2,5))

reshape arr1 [[0 1 2 3 4]
 [5 6 7 8 9]]
reshape arr2 [[3 4]
 [5 1]
 [2 5]]
reshape arr3 [[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]]


In [ ]:
print(np.empty((3,3)))

# numpy functions

In [43]:
print(np.zeros((3,3), dtype=int))
print('___'*10)
print(np.ones((3,3), dtype=complex))
print('___'*10)
print(np.full((3,3), 52))
print('___'*10)
print(np.eye(4))
print('___'*10)
print(np.random.random((3,3)))
print('___'*10)
print(np.random.randint(0, 11, (3,3)))
print('___'*10)
print(np.linspace(0, 10, 5))
print('___'*10)
print(np.arange(0, 10, 2))
print('___'*10)
print(np.cos(np.linspace(0, np.pi, 3)))
print('___'*10)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
______________________________
[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]
______________________________
[[52 52 52]
 [52 52 52]
 [52 52 52]]
______________________________
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
______________________________
[[0.0130961  0.90015854 0.83062329]
 [0.14140271 0.40997063 0.36854863]
 [0.49623057 0.58915607 0.07017417]]
______________________________
[[ 5  0  2]
 [ 4  6  9]
 [10  7  4]]
______________________________
[ 0.   2.5  5.   7.5 10. ]
______________________________
[0 2 4 6 8]
______________________________
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
______________________________
