### create a 2-dimensional integer array of size 3x3, complete randomly, print the 2nd line and print the first column.

In [62]:
import numpy as np
arr = np.random.randint(0, 10, (3,3))
print(f"arr: {arr}")
print(f"2nd line: {arr[1]}")
print(f"first column: {arr[:,0]}")

arr: [[6 0 1]
 [3 9 9]
 [1 0 1]]
2nd line: [3 9 9]
first column: [6 3 1]


In [69]:
### create an array of integer in range 2 to 13 and print their logarithm and their square root

In [72]:
arr = np.arange(2, 14)
print(f"arr: {arr}")
print(f"log: {np.log(arr)}")
print(f"sqrt: {np.sqrt(arr)}")

arr: [ 2  3  4  5  6  7  8  9 10 11 12 13]
log: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015
 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665 2.56494936]
sqrt: [1.41421356 1.73205081 2.         2.23606798 2.44948974 2.64575131
 2.82842712 3.         3.16227766 3.31662479 3.46410162 3.60555128]


modify the previous array to be a 3x4 dimensional matrix

In [73]:
print(arr.reshape(3,4))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
