# Debutant

In [2]:
import numpy as np


In [9]:
# un tableau de 10 zeros
zeros = np.zeros(10, dtype=int)
print(zeros)

[0 0 0 0 0 0 0 0 0 0]


In [10]:
# un tableau de 10 uns
ones = np.ones(10, dtype=int)
print(ones)

[1 1 1 1 1 1 1 1 1 1]


In [8]:
# un tableau contenant les nombres de 1 a 10
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
# un tableau de 10 nombres aleatoire entre 0 à 1
arr = np.random.random(size=10)
print(arr)

[0.2402163  0.2650349  0.11346201 0.23655214 0.05090717 0.12741703
 0.28442898 0.16728664 0.30134598 0.15644409]


In [21]:
# un tableau de 10 nombres aléatoires entre 10 à 100
arr = np.random.uniform(10, 100, size=10)
print(arr)

[87.50805932 73.590984   22.96299867 13.61499228 80.59311411 90.28341386
 92.36687571 14.24927539 12.45943002 93.03772671]


In [19]:
# modification d'un tableau, prend un tableau de [1, 2, 3, 4, 5] et multiplie par deux
arr = np.arange(1, 6)
print(arr)
arr = arr * 2
print(arr)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [6]:
# extrait les éléments supérieurs à 50 dans un tableau de 20 nombres aléatoires entre 0 et 100
arr = np.random.randint(0, 100, size=20)
print(arr)
print(arr[arr > 50])

[33 87 51 42  2 17 85 24 56 57 63 17 37 46 44  6 10 11 50 69]
[87 51 85 56 57 63 69]


# Intermédiaire

In [23]:
# Création et manipulation d'une matrice
#→ Crée une matrice 3×3 de nombres entiers aléatoires entre 1 et 50 et remplace la diagonale principale par des 0.
matrice = np.array([
    np.random.randint(1, 50, size=9),
])
matrice = matrice.reshape(3, 3)
print(matrice)
print('___'*10)

np.fill_diagonal(matrice, 0)

# for i in range(len(matrice)):
#     for j in range(len(matrice[i])):
#         if i == j:
#             matrice[i][j] = 0
print(matrice)


[[30 23 45]
 [20 24 33]
 [39 43 14]]
______________________________
[[ 0 23 45]
 [20  0 33]
 [39 43  0]]


In [29]:
# somme et moyenne d'un tableau
#→ Crée un tableau de 100 nombres aléatoires entre 0 et 500 et affiche sa somme et sa moyenne.
tab = np.array(np.random.randint(0, 500, size=100))
print(tab)
print('_'*10)
print(tab.sum())
print('_'*10)
print(tab.mean())

[252 113 246 494  74 259 211 150  16 157  87 143 455 199 395 455  16 378
 328 354 295 321 237 184 466  56 400 104 279 445 169 353 338 169 263  39
 401 418  22 131  21 205  81 136 233 309 179 162  45 262 370   5 166 450
 328 364  56 429  78 448 349 207 421 470 476 474 109 194  99 481 309 136
  53 427 422 419 271  91 495 151 101 169 389  21 358 102   0 375 177 378
 274 444 372 368 158 472  44 262 471 176]
__________
25364
__________
253.64
