# Debutant

In [2]:
import numpy as np


In [9]:
# un tableau de 10 zeros
zeros = np.zeros(10, dtype=int)
print(zeros)

[0 0 0 0 0 0 0 0 0 0]


In [10]:
# un tableau de 10 uns
ones = np.ones(10, dtype=int)
print(ones)

[1 1 1 1 1 1 1 1 1 1]


In [8]:
# un tableau contenant les nombres de 1 a 10
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
# un tableau de 10 nombres aleatoire entre 0 à 1
arr = np.random.random(size=10)
print(arr)

[0.2402163  0.2650349  0.11346201 0.23655214 0.05090717 0.12741703
 0.28442898 0.16728664 0.30134598 0.15644409]


In [21]:
# un tableau de 10 nombres aléatoires entre 10 à 100
arr = np.random.uniform(10, 100, size=10)
print(arr)

[87.50805932 73.590984   22.96299867 13.61499228 80.59311411 90.28341386
 92.36687571 14.24927539 12.45943002 93.03772671]


In [19]:
# modification d'un tableau, prend un tableau de [1, 2, 3, 4, 5] et multiplie par deux
arr = np.arange(1, 6)
print(arr)
arr = arr * 2
print(arr)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [6]:
# extrait les éléments supérieurs à 50 dans un tableau de 20 nombres aléatoires entre 0 et 100
arr = np.random.randint(0, 100, size=20)
print(arr)
print(arr[arr > 50])

[33 87 51 42  2 17 85 24 56 57 63 17 37 46 44  6 10 11 50 69]
[87 51 85 56 57 63 69]


# Intermédiaire

In [6]:
# Création et manipulation d'une matrice
#→ Crée une matrice 3×3 de nombres entiers aléatoires entre 1 et 50 et remplace la diagonale principale par des 0.
matrice = np.random.randint(1, 50, (3, 3))

print(matrice)
print('___'*10)

np.fill_diagonal(matrice, 0)

# for i in range(len(matrice)):
#     for j in range(len(matrice[i])):
#         if i == j:
#             matrice[i][j] = 0
print(matrice)


[[26  7 37]
 [22 24  6]
 [ 1 28 44]]
______________________________
[[ 0  7 37]
 [22  0  6]
 [ 1 28  0]]


In [3]:
# somme et moyenne d'un tableau
#→ Crée un tableau de 100 nombres aléatoires entre 0 et 500 et affiche sa somme et sa moyenne.
tab = np.array(np.random.randint(0, 500, size=100))
print(tab)
print('_'*10)
print(tab.sum())
print('_'*10)
print(tab.mean())

[364 286 123  67 428  71 456 272 430 263 170 163 216 365 318 189  72 441
 285 276 490 414 378 100 402 165 186 430 253  46  38 242  78 135 426  51
  35  34 164 183 367 415 390 179 397 333 284 493 322 438 273 227 150  70
 382 194 344 475 135 405 235  90 386 376 377 222 372 430 191 112 327   3
 359 259  44 190 373 223 303 258  60 218 393 455  70  43 249 483 429 474
  77 460 127 103 306 438 393 141 158 222]
__________
26207
__________
262.07


In [5]:
# Trouver les valeurs maximales et minimales
#→ Génère un tableau de 20 nombres aléatoires et trouve les indices de la valeur maximale et minimale.
tab = np.random.randint(0, 100, size=20)
index_max = np.argmax(tab)
index_min = np.argmin(tab)
print(tab)
print('_'*10)
print(index_max)
print('_'*10)
print(index_min)

[60 48 96  6 11 14 35 94 66 58 88 97 56 51 68 32 96 67 42  8]
__________
11
__________
3


In [7]:
# Filtrage de valeurs
#→ Crée un tableau de 15 valeurs entre 1 et 100 et ne conserve que les valeurs paires
tab = np.random.randint(1, 100, size=15)
paires = tab[tab % 2 == 0 ]
print(paires)
print('_'*10)
print(tab)


[32 26 10 30 20  8 30]
__________
[45 32 26 10 30 20  8 91 77 43 33 81 89 51 30]
